### ISSUE TITLE
Error when showing the dialog

### ISSUE THREAD

**Issue by AminEsmaeily** [iammohdzaki/KnotFileChooser-Android#2]
I use the KnokFileChooser in my Java class, and when I call the `show` method, it shows me the following exception:
```
android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class TextView
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f030205 a=-1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
        at android.widget.TextView.<init>(TextView.java:1076)
        at android.widget.TextView.<init>(TextView.java:704)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.afollestad.materialdialogs.MaterialDialog$Builder.customView(MaterialDialog.java:1825)
        at com.zaphlabs.filechooser.KnotFileChooser$DialogBuilder.<init>(KnotFileChooser.kt:351)
        at com.zaphlabs.filechooser.KnotFileChooser.show(KnotFileChooser.kt:315)
```

I call it like this:
``` java
new KnotFileChooser(this,
                false,
                true,
                Environment.getExternalStorageDirectory(),
                true,
                0,
                0,
                false,
                true,
                true,
                true,
                true,
                false,
                true,
                FileType.ALL)
                .title(R.string.choose_folder)
                .sorter(Sorter.ByNameInAscendingOrder.INSTANCE)
                .show();
```

**Comment by metalichesky** [comment]
> I use the KnokFileChooser in my Java class, and when I call the `show` method, it shows me the following exception:
> 
> ```
> android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class TextView
>     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class TextView
>     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f030205 a=-1}
>         at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
>         at android.widget.TextView.<init>(TextView.java:1076)
>         at android.widget.TextView.<init>(TextView.java:704)
>         at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
>         at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
>         at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
>         at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
>         at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
>         at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
>         at com.afollestad.materialdialogs.MaterialDialog$Builder.customView(MaterialDialog.java:1825)
>         at com.zaphlabs.filechooser.KnotFileChooser$DialogBuilder.<init>(KnotFileChooser.kt:351)
>         at com.zaphlabs.filechooser.KnotFileChooser.show(KnotFileChooser.kt:315)
> ```
> 
> I call it like this:
> 
> ```java
> new KnotFileChooser(this,
>                 false,
>                 true,
>                 Environment.getExternalStorageDirectory(),
>                 true,
>                 0,
>                 0,
>                 false,
>                 true,
>                 true,
>                 true,
>                 true,
>                 false,
>                 true,
>                 FileType.ALL)
>                 .title(R.string.choose_folder)
>                 .sorter(Sorter.ByNameInAscendingOrder.INSTANCE)
>                 .show();
> ```

Unfortunately i just ran into the same problem

**Comment by metalichesky** [comment]
@AminEsmaeily I found a temporary solution.
I overridden all the specified values ​​in AppTheme:
        \<item name="kfc_theme_background">@color/corDefundo\</item>
        \<item name="kfc_theme_foreground">@color/colorPrimary\</item>
        \<item name="kfc_theme_title">@color/cinzaEscuro\</item>
        \<item name="kfc_theme_breadcrumb">@color/azulClaro\</item>
        \<item name="kfc_theme_toolbox">@color/colorPrimary\</item>
        \<item name="kfc_theme_search_text">@color/cinzaEscuro\</item>
        \<item name="kfc_theme_search_hint">@color/cinzaClaro\</item>
        \<item name="kfc_theme_status">@color/colorPrimary\</item>
        \<item name="kfc_theme_file_icon">@color/colorPrimary\</item>
        \<item name="kfc_theme_file_name">@color/colorPrimary\</item>
        \<item name="kfc_theme_file_information">@color/colorAccent\</item>
        \<item name="kfc_theme_file_flag">@color/cinzaClaro\</item>
        \<item name="kfc_theme_file_asterisk">@color/amarelo\</item>
        \<item name="kfc_theme_checkbox">@color/colorAccent\</item>
        \<item name="kfc_theme_cancel_button">@color/colorAccent\</item>
        \<item name="kfc_theme_ok_button">@color/colorAccent\</item>
        \<item name="kfc_theme_create_folder_button">@color/verde\</item>
(course, you should use your own colors)
Also I also added a dependency to the build.gradle of app module:
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'

@iammohdzaki thank's for good library! And I hope in a future version you will be able to fix this bug.

**Comment by iammohdzaki** [comment]
Currently you have to override the styles values.
Will fix in future.
