### ISSUE TITLE
Not compatible with Android 10 API 29

### ISSUE THREAD

**Issue by sanjaykumarm** [iammohdzaki/KnotFileChooser-Android#3]
Library's target SDK is set to API 29 (Android 10), but it is not working on Android 10. I think it should be resolved immediately as so many Android 10 devices are there in market today.

**Comment by iammohdzaki** [comment]
What issue are you facing @sanjaykumarm

**Comment by sanjaykumarm** [comment]
If you change the target SDK version to 29, then it is not listing all the directories in Android 10 due to file system is not working in android 10, that recently changed in android 10. So can you please provide the support to that by setting target SDK to andrtoid 10. It would be a great help and mke this library robust as google want to target all the apps to android 10 in coming days.

**Comment by iammohdzaki** [comment]
Found the fix 
Add this in your manifest
android:requestLegacyExternalStorage="true"
for Android 10

**Comment by sanjaykumarm** [comment]
@iammohdzaki That solution is for legacy support. But near November 2020, all application must set to target SDK to 29 and after that this legacy support will be removed. So it is not the proper solution of the problem.
